version: 0.2
dictionary:
  - en_US
matrix:
  - name: Markdown
    sources:
      - "**/*.md"
  # - name: Python
  #   sources:
  #     - "**/*.py"
exclude:
  - "*.ipynb"
  - "node_modules/**"
  - "dist/**"
  - ".git/**"
  - ".github/workflows/**"
